application: thedivisionlatinolfg
version: 1
runtime: go
api_version: go1

handlers:
- url: /assets
  static_dir: assets

- url: /favicon\.ico
  static_files: assets/favicon\.ico
  upload: assets/favicon\.ico

- url: /.*
  script: _go_app