application: thedivisionlatinolfg
version: 1
runtime: go
api_version: go1

handlers:
- url: /assets
  static_dir: assets
- url: /favicon.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico
- url: /robots.txt
  static_files: assets/robots.txt
  upload: assets/robots.txt
- url: /.*
  script: _go_app

skip_files:
- ^(.*/)?.*\.DS_Store$
- ^(.*/)?.*/node_modules/.*$